apiVersion: v1
kind: Namespace
metadata:
  name: helm-guestbook
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
  annotations:
    argocd.argoproj.io/sync-wave: "-1"